/*
 * Friend boost GM utilities for small-group catch-up characters.
 */

#include "Chat.h"
#include "CommandScript.h"
#include "Bag.h"
#include "Item.h"
#include "ObjectGuid.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "PlayerbotAIConfig.h"
#include "PlayerbotFactory.h"
#include "World.h"

#include <algorithm>
#include <vector>

using namespace Acore::ChatCommands;

namespace
{
constexpr uint32 CatchupBagItemId = 4245;
constexpr uint8 CatchupBagSlots = 10;
constexpr uint8 GearReplacementLevelGap = 5;

struct ProtectedEquipment
{
    uint8 Slot;
    ObjectGuid Guid;
};

uint32 GetCatchupItemLevel(ItemTemplate const* itemTemplate)
{
    if (!itemTemplate)
        return 0;

    if (itemTemplate->RequiredLevel > 0)
        return itemTemplate->RequiredLevel;

    return itemTemplate->ItemLevel;
}

bool IsVeryOutdatedForBoost(Item* item, uint8 targetLevel)
{
    if (!item)
        return true;

    uint32 const threshold = targetLevel > GearReplacementLevelGap
        ? targetLevel - GearReplacementLevelGap : 0;

    return GetCatchupItemLevel(item->GetTemplate()) <= threshold;
}

std::vector<ProtectedEquipment> SnapshotProtectedEquipment(
    Player* player, uint8 targetLevel)
{
    std::vector<ProtectedEquipment> protectedEquipment;

    for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_END; ++slot)
    {
        if (slot == EQUIPMENT_SLOT_BODY || slot == EQUIPMENT_SLOT_TABARD)
            continue;

        Item* item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
        if (item && !IsVeryOutdatedForBoost(item, targetLevel))
            protectedEquipment.push_back({ slot, item->GetGUID() });
    }

    return protectedEquipment;
}

void DestroyEquippedItem(Player* player, uint8 slot)
{
    Item* item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
    if (!item)
        return;

    player->DestroyItem(INVENTORY_SLOT_BAG_0, slot, true);
}

void RestoreProtectedEquipment(
    Player* player, std::vector<ProtectedEquipment> const& protectedEquipment)
{
    for (ProtectedEquipment const& protectedItem : protectedEquipment)
    {
        Item* equipped = player->GetItemByPos(
            INVENTORY_SLOT_BAG_0, protectedItem.Slot);
        if (equipped && equipped->GetGUID() == protectedItem.Guid)
            continue;

        Item* original = player->GetItemByGuid(protectedItem.Guid);
        if (!original)
            continue;

        uint16 destination = 0;
        if (player->CanEquipItem(protectedItem.Slot, destination, original,
            true) != EQUIP_ERR_OK)
            continue;

        // The replacement was just generated by the boost. Throw it away and
        // put the player's still-good item back on.
        DestroyEquippedItem(player, protectedItem.Slot);

        if (player->CanEquipItem(protectedItem.Slot, destination, original,
            false) != EQUIP_ERR_OK)
            continue;

        player->RemoveItem(original->GetBagSlot(), original->GetSlot(), true);
        player->EquipItem(destination, original, true);
    }
}

bool IsBagEmpty(Bag const* bag)
{
    if (!bag)
        return true;

    for (uint8 slot = 0; slot < bag->GetBagSize(); ++slot)
        if (bag->GetItemByPos(slot))
            return false;

    return true;
}

void InitCatchupBags(Player* player)
{
    if (!sObjectMgr->GetItemTemplate(CatchupBagItemId))
        return;

    for (uint8 slot = INVENTORY_SLOT_BAG_START;
        slot < INVENTORY_SLOT_BAG_END; ++slot)
    {
        Item* oldItem = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
        if (oldItem)
        {
            Bag* oldBag = oldItem->ToBag();
            if (!oldBag || oldBag->GetBagSize() >= CatchupBagSlots ||
                !IsBagEmpty(oldBag))
                continue;

            player->DestroyItem(INVENTORY_SLOT_BAG_0, slot, true);
        }

        uint16 destination = 0;
        if (player->CanEquipNewItem(slot, destination, CatchupBagItemId,
            false) == EQUIP_ERR_OK)
            player->EquipNewItem(destination, CatchupBagItemId, true);
    }
}

void SetBoostSkill(Player* player, uint16 skillId, uint8 targetLevel)
{
    uint32 const maxValue = targetLevel * 5;
    uint16 const step = player->GetSkillValue(skillId)
        ? player->GetSkillStep(skillId) : 1;

    player->SetSkill(skillId, step, maxValue, maxValue);
}

void InitBoostCombatSkills(Player* player, uint8 targetLevel)
{
    player->UpdateSkillsForLevel();

    player->SetSkill(SKILL_RIDING, 0, 0, 0);
    if (player->GetLevel() >= sPlayerbotAIConfig.useGroundMountAtMinLevel)
        player->learnSpell(33388);
    if (player->GetLevel() >= sPlayerbotAIConfig.useFastGroundMountAtMinLevel)
        player->learnSpell(33391);
    if (player->GetLevel() >= sPlayerbotAIConfig.useFlyMountAtMinLevel)
        player->learnSpell(34090);
    if (player->GetLevel() >= sPlayerbotAIConfig.useFastFlyMountAtMinLevel)
        player->learnSpell(34091);

    uint32 const armorSkillLevel = player->GetLevel() < 40 ? 0 : 1;
    uint32 const dualWieldLevel = player->GetLevel() < 20 ? 0 : 1;
    SetBoostSkill(player, SKILL_DEFENSE, targetLevel);
    SetBoostSkill(player, SKILL_UNARMED, targetLevel);

    switch (player->getClass())
    {
        case CLASS_DRUID:
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_2H_MACES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_POLEARMS, targetLevel);
            SetBoostSkill(player, SKILL_FIST_WEAPONS, targetLevel);
            break;
        case CLASS_WARRIOR:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_BOWS, targetLevel);
            SetBoostSkill(player, SKILL_GUNS, targetLevel);
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_2H_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_AXES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_CROSSBOWS, targetLevel);
            SetBoostSkill(player, SKILL_POLEARMS, targetLevel);
            SetBoostSkill(player, SKILL_FIST_WEAPONS, targetLevel);
            SetBoostSkill(player, SKILL_THROWN, targetLevel);
            player->SetSkill(
                SKILL_DUAL_WIELD, 0, dualWieldLevel, dualWieldLevel);
            player->SetSkill(
                SKILL_PLATE_MAIL, 0, armorSkillLevel, armorSkillLevel);
            player->SetCanDualWield(dualWieldLevel != 0);
            break;
        case CLASS_PALADIN:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_2H_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_AXES, targetLevel);
            SetBoostSkill(player, SKILL_POLEARMS, targetLevel);
            player->SetSkill(
                SKILL_PLATE_MAIL, 0, armorSkillLevel, armorSkillLevel);
            break;
        case CLASS_PRIEST:
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_WANDS, targetLevel);
            break;
        case CLASS_SHAMAN:
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_2H_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_AXES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_FIST_WEAPONS, targetLevel);
            player->SetSkill(SKILL_MAIL, 0, armorSkillLevel, armorSkillLevel);
            break;
        case CLASS_MAGE:
        case CLASS_WARLOCK:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_WANDS, targetLevel);
            break;
        case CLASS_HUNTER:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_BOWS, targetLevel);
            SetBoostSkill(player, SKILL_GUNS, targetLevel);
            SetBoostSkill(player, SKILL_2H_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_STAVES, targetLevel);
            SetBoostSkill(player, SKILL_2H_AXES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_CROSSBOWS, targetLevel);
            SetBoostSkill(player, SKILL_POLEARMS, targetLevel);
            SetBoostSkill(player, SKILL_FIST_WEAPONS, targetLevel);
            SetBoostSkill(player, SKILL_THROWN, targetLevel);
            player->SetSkill(
                SKILL_DUAL_WIELD, 0, dualWieldLevel, dualWieldLevel);
            player->SetSkill(SKILL_MAIL, 0, armorSkillLevel, armorSkillLevel);
            player->SetCanDualWield(dualWieldLevel != 0);
            break;
        case CLASS_ROGUE:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_BOWS, targetLevel);
            SetBoostSkill(player, SKILL_GUNS, targetLevel);
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_DAGGERS, targetLevel);
            SetBoostSkill(player, SKILL_CROSSBOWS, targetLevel);
            SetBoostSkill(player, SKILL_FIST_WEAPONS, targetLevel);
            SetBoostSkill(player, SKILL_THROWN, targetLevel);
            SetBoostSkill(player, SKILL_LOCKPICKING, targetLevel);
            player->SetSkill(SKILL_DUAL_WIELD, 0, 1, 1);
            player->SetCanDualWield(true);
            break;
        case CLASS_DEATH_KNIGHT:
            SetBoostSkill(player, SKILL_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_AXES, targetLevel);
            SetBoostSkill(player, SKILL_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_SWORDS, targetLevel);
            SetBoostSkill(player, SKILL_2H_MACES, targetLevel);
            SetBoostSkill(player, SKILL_2H_AXES, targetLevel);
            SetBoostSkill(player, SKILL_POLEARMS, targetLevel);
            player->SetSkill(
                SKILL_DUAL_WIELD, 0, dualWieldLevel, dualWieldLevel);
            player->SetCanDualWield(dualWieldLevel != 0);
            break;
        default:
            break;
    }
}
}

class friend_boost_commandscript : public CommandScript
{
public:
    friend_boost_commandscript() :
        CommandScript("friend_boost_commandscript") { }

    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable commandTable =
        {
            { "boost", HandleBoostCommand, SEC_GAMEMASTER, Console::No }
        };

        return commandTable;
    }

    static bool HandleBoostCommand(
        ChatHandler* handler, Optional<PlayerIdentifier> target, uint8 level)
    {
        if (!target)
            target = PlayerIdentifier::FromTargetOrSelf(handler);

        if (!target || !target->IsConnected())
        {
            handler->PSendSysMessage(
                "Usage: .boost [player] <level>. Target must be online.");
            return false;
        }

        Player* player = target->GetConnectedPlayer();
        if (handler->HasLowerSecurity(player))
            return false;

        uint32 maxLevel = std::min<uint32>(
            sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL), DEFAULT_MAX_LEVEL);
        if (level < 1 || level > maxLevel)
        {
            handler->PSendSysMessage(
                "Boost level must be between 1 and {}.", maxLevel);
            return false;
        }

        player->CombatStop(true);
        if (player->isDead())
            player->ResurrectPlayer(1.0f, false);

        player->GiveLevel(level);
        player->InitTalentForLevel();
        player->SetUInt32Value(PLAYER_XP, 0);
        player->InitStatsForLevel(true);
        player->LearnDefaultSkills();
        std::vector<ProtectedEquipment> protectedEquipment =
            SnapshotProtectedEquipment(player, level);

        PlayerbotFactory factory(player, level, ITEM_QUALITY_RARE, 0);
        InitBoostCombatSkills(player, level);
        factory.InitClassSpells();
        factory.InitAvailableSpells();
        factory.InitSpecialSpells();
        factory.InitTalentsTree(false, true, true);
        factory.InitMounts();
        InitCatchupBags(player);

        float previousGearLoweringChance =
            sPlayerbotAIConfig.randomGearLoweringChance;
        sPlayerbotAIConfig.randomGearLoweringChance = 0.90f;
        factory.InitEquipment(false, false);
        sPlayerbotAIConfig.randomGearLoweringChance =
            previousGearLoweringChance;
        RestoreProtectedEquipment(player, protectedEquipment);

        factory.InitAmmo();
        factory.InitFood();
        factory.InitPotions();
        factory.InitReagents();
        factory.InitConsumables();
        factory.InitGlyphs();
        factory.InitPet();
        factory.InitPetTalents();
        factory.InitKeyring();
        factory.InitReputation();

        if (player->GetLevel() >= sPlayerbotAIConfig.minEnchantingBotLevel)
            factory.ApplyEnchantAndGemsNew(false);

        uint64 const starterMoney = uint64(level) * 10000;
        if (player->GetMoney() < starterMoney)
            player->SetMoney(starterMoney);

        player->DurabilityRepairAll(false, 1.0f, false);
        player->SetHealth(player->GetMaxHealth());
        player->SetPower(POWER_MANA, player->GetMaxPower(POWER_MANA));
        player->SaveToDB(false, false);

        handler->PSendSysMessage(
            "Boosted {} to level {} with conservative catch-up gear, skills, "
            "spells, consumables, bags, mounts, and talents.",
            handler->playerLink(*target), level);

        if (handler->needReportToTarget(player))
            ChatHandler(player->GetSession()).PSendSysMessage(
                "{} boosted you to level {} and prepared your gear and "
                "supplies.",
                handler->GetNameLink(), level);

        return true;
    }
};

void Addmod_friend_boostScripts()
{
    new friend_boost_commandscript();
}
